[package]
name = "rooney"
version = "0.1.0"
authors = ["nemo <nemo@redbrick.dcu.ie>"]
edition = "2018"

[dependencies]
chrono = "0.4.0"
irc = "0.13"
log = "0.4.6"
postgres = {version = "0.15.2", features = ["with-chrono"]}
separator = "0.3.1"
std-logger = "0.3.3"
titlecase = "0.9"
